smoovio_api:
    resource: "@SmoovioApiBundle/Controller/"
    type:     annotation
    prefix:   /api

smoovio_portal:
    resource: "@SmoovioPortalBundle/Resources/config/routing.yml"
    prefix:   /

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
